# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Knock on Wood
tagline:             'carpenta.github.io jekyll blog'
description:         'carpenta.github.io jekyll blog'
url:                 http://carpenta.github.io
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              Ian Cho
  url:               https://twitter.com/carpenta
  email:             bthedream@daum.net

# Custom vars
version:             1.0.0
