# Site settings
title: "Woodstock"
description: "create something.."
baseurl: ""
url: "carpenta.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "abt"
    url: /about
  - title: "twt"
    url: http://twitter.com/carpenta
  - title: "git"
    url: http://github.com/carpenta
#  - title: "rss"
#    url: /feed.xml
