# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Carpenta
tagline:          'github, blog'
description:      'Carpenta github.io jekyll blog'
url:              http://carpenta.github.io
baseurl:          /

author:
  name:           'ian'
  url:            https://twitter.com/carpenta

paginate:         5

# Custom vars
version:          1.0
